import type { User, Book, Transaction, Reservation, DashboardStats, Category, Branch } from "./types"

// Mock Users
export const mockUsers: User[] = [
  {
    id: "1",
    email: "admin@library.com",
    name: "Admin User",
    role: "admin",
    membershipId: "ADM001",
    phone: "555-0100",
    address: "123 Library Lane",
    joinDate: "2023-01-01",
    borrowingLimit: 20,
    currentBorrows: 0,
    finesOwed: 0,
    isActive: true,
  },
  {
    id: "2",
    email: "librarian@library.com",
    name: "Sarah Johnson",
    role: "librarian",
    membershipId: "LIB001",
    phone: "555-0101",
    address: "456 Book Street",
    joinDate: "2023-03-15",
    borrowingLimit: 15,
    currentBorrows: 2,
    finesOwed: 0,
    isActive: true,
  },
  {
    id: "3",
    email: "john@email.com",
    name: "John Smith",
    role: "patron",
    membershipId: "PAT001",
    phone: "555-0102",
    address: "789 Reader Road",
    joinDate: "2023-06-20",
    borrowingLimit: 5,
    currentBorrows: 3,
    finesOwed: 5.5,
    isActive: true,
  },
  {
    id: "4",
    email: "emma@email.com",
    name: "Emma Wilson",
    role: "patron",
    membershipId: "PAT002",
    phone: "555-0103",
    address: "321 Novel Avenue",
    joinDate: "2023-08-10",
    borrowingLimit: 5,
    currentBorrows: 1,
    finesOwed: 0,
    isActive: true,
  },
  {
    id: "5",
    email: "michael@email.com",
    name: "Michael Brown",
    role: "patron",
    membershipId: "PAT003",
    phone: "555-0104",
    address: "654 Story Street",
    joinDate: "2024-01-05",
    borrowingLimit: 5,
    currentBorrows: 0,
    finesOwed: 12.0,
    isActive: true,
  },
  {
    id: "6",
    email: "newuser@email.com",
    name: "New User",
    role: "patron",
    membershipId: "PAT004",
    phone: "555-0105",
    address: "123 New Street",
    joinDate: new Date().toISOString().split("T")[0],
    borrowingLimit: 5,
    currentBorrows: 0,
    finesOwed: 0,
    isActive: false,
    approvalStatus: "pending",
  },
]

// Mock Branches
export const mockBranches: Branch[] = [
  {
    id: "1",
    name: "Main Library",
    address: "123 Library Lane, Booktown",
    phone: "(555) 123-4567",
    email: "main@libraryhub.com",
    isActive: true,
  },
  {
    id: "2",
    name: "North Branch",
    address: "456 North Street, Booktown",
    phone: "(555) 123-4568",
    email: "north@libraryhub.com",
    isActive: true,
  },
  {
    id: "3",
    name: "South Branch",
    address: "789 South Avenue, Booktown",
    phone: "(555) 123-4569",
    email: "south@libraryhub.com",
    isActive: true,
  },
]

// Mock Books
export const mockBooks: Book[] = [
  {
    id: "1",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    isbn: "978-0743273565",
    category: "Fiction",
    genre: "Classic Literature",
    publisher: "Scribner",
    publishYear: 1925,
    description: "A story of decadence and excess, Gatsby explores the American Dream in the Jazz Age.",
    coverImage: "/great-gatsby-book-cover.png",
    totalCopies: 5,
    availableCopies: 3,
    status: "available",
    location: "A-12-3",
    addedDate: "2023-01-15",
    deweyClassification: "813.52",
  },
  {
    id: "2",
    title: "1984",
    author: "George Orwell",
    isbn: "978-0451524935",
    category: "Fiction",
    genre: "Dystopian",
    publisher: "Signet Classic",
    publishYear: 1949,
    description: "A dystopian social science fiction novel and cautionary tale about totalitarianism.",
    coverImage: "/1984-orwell-book-cover.jpg",
    totalCopies: 4,
    availableCopies: 1,
    status: "available",
    location: "A-12-4",
    addedDate: "2023-02-20",
    deweyClassification: "823.912",
  },
  {
    id: "3",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    isbn: "978-0060935467",
    category: "Fiction",
    genre: "Southern Gothic",
    publisher: "Harper Perennial",
    publishYear: 1960,
    description: "A novel about racial injustice and the loss of innocence in the American South.",
    coverImage: "/to-kill-a-mockingbird-cover.png",
    totalCopies: 6,
    availableCopies: 4,
    status: "available",
    location: "A-13-1",
    addedDate: "2023-03-10",
    deweyClassification: "813.54",
  },
  {
    id: "4",
    title: "Clean Code",
    author: "Robert C. Martin",
    isbn: "978-0132350884",
    category: "Technology",
    genre: "Programming",
    publisher: "Prentice Hall",
    publishYear: 2008,
    description: "A handbook of agile software craftsmanship with practical approaches to writing clean code.",
    coverImage: "/clean-code-programming-book-cover.jpg",
    totalCopies: 3,
    availableCopies: 0,
    status: "borrowed",
    location: "C-05-2",
    addedDate: "2023-04-05",
    deweyClassification: "005.1",
  },
  {
    id: "5",
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    isbn: "978-0553380163",
    category: "Science",
    genre: "Physics",
    publisher: "Bantam",
    publishYear: 1988,
    description: "A landmark volume in science writing exploring the nature of time and the universe.",
    coverImage: "/brief-history-of-time-hawking-book-cover.jpg",
    totalCopies: 2,
    availableCopies: 2,
    status: "available",
    location: "B-08-3",
    addedDate: "2023-05-18",
    deweyClassification: "523.1",
  },
  {
    id: "6",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    isbn: "978-0141439518",
    category: "Fiction",
    genre: "Romance",
    publisher: "Penguin Classics",
    publishYear: 1813,
    description:
      "A romantic novel of manners that follows Elizabeth Bennet as she deals with issues of society and love.",
    coverImage: "/pride-and-prejudice-austen-book-cover.jpg",
    totalCopies: 4,
    availableCopies: 3,
    status: "available",
    location: "A-14-2",
    addedDate: "2023-06-22",
    deweyClassification: "823.7",
  },
  {
    id: "7",
    title: "The Design of Everyday Things",
    author: "Don Norman",
    isbn: "978-0465050659",
    category: "Design",
    genre: "UX Design",
    publisher: "Basic Books",
    publishYear: 2013,
    description: "A powerful primer on how design serves as the communication between object and user.",
    coverImage: "/design-of-everyday-things-book-cover.jpg",
    totalCopies: 2,
    availableCopies: 1,
    status: "available",
    location: "D-02-1",
    addedDate: "2023-07-30",
    deweyClassification: "745.2",
  },
  {
    id: "8",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    isbn: "978-0062316097",
    category: "History",
    genre: "World History",
    publisher: "Harper",
    publishYear: 2015,
    description: "A survey of the history of humankind from the Stone Age to the present.",
    coverImage: "/sapiens-harari-book-cover.jpg",
    totalCopies: 5,
    availableCopies: 2,
    status: "available",
    location: "B-03-4",
    addedDate: "2023-08-14",
    deweyClassification: "909",
  },
]

// Mock Transactions
export const mockTransactions: Transaction[] = [
  {
    id: "1",
    userId: "3",
    userName: "John Smith",
    bookId: "4",
    bookTitle: "Clean Code",
    type: "borrow",
    status: "active",
    issueDate: "2024-12-01",
    dueDate: "2024-12-15",
    renewCount: 0,
    fine: 0,
    finePaid: false,
  },
  {
    id: "2",
    userId: "3",
    userName: "John Smith",
    bookId: "2",
    bookTitle: "1984",
    type: "borrow",
    status: "overdue",
    issueDate: "2024-11-15",
    dueDate: "2024-11-29",
    renewCount: 1,
    fine: 5.5,
    finePaid: false,
  },
  {
    id: "3",
    userId: "4",
    userName: "Emma Wilson",
    bookId: "8",
    bookTitle: "Sapiens: A Brief History of Humankind",
    type: "borrow",
    status: "active",
    issueDate: "2024-12-05",
    dueDate: "2024-12-19",
    renewCount: 0,
    fine: 0,
    finePaid: false,
  },
  {
    id: "4",
    userId: "2",
    userName: "Sarah Johnson",
    bookId: "1",
    bookTitle: "The Great Gatsby",
    type: "borrow",
    status: "returned",
    issueDate: "2024-11-01",
    dueDate: "2024-11-15",
    returnDate: "2024-11-14",
    renewCount: 0,
    fine: 0,
    finePaid: false,
  },
]

// Mock Reservations
export const mockReservations: Reservation[] = [
  {
    id: "1",
    userId: "5",
    userName: "Michael Brown",
    bookId: "4",
    bookTitle: "Clean Code",
    reserveDate: "2024-12-03",
    queuePosition: 1,
    status: "pending",
    notificationSent: false,
  },
  {
    id: "2",
    userId: "3",
    userName: "John Smith",
    bookId: "7",
    bookTitle: "The Design of Everyday Things",
    reserveDate: "2024-12-08",
    queuePosition: 1,
    status: "ready",
    notificationSent: true,
  },
]

// Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  totalBooks: 31,
  totalMembers: 156,
  activeLoans: 45,
  overdueBooks: 8,
  reservations: 12,
  finesCollected: 234.5,
  newMembersThisMonth: 12,
  booksAddedThisMonth: 8,
}

// Categories
export const mockCategories: Category[] = [
  { id: "1", name: "Fiction", count: 145 },
  { id: "2", name: "Technology", count: 78 },
  { id: "3", name: "Science", count: 56 },
  { id: "4", name: "History", count: 43 },
  { id: "5", name: "Design", count: 32 },
  { id: "6", name: "Biography", count: 28 },
  { id: "7", name: "Self-Help", count: 24 },
  { id: "8", name: "Children", count: 19 },
]
